# Based on https://kubernetes.io/docs/reference/access-authn-authz/rbac/
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  namespace: my-scm
  name: deployment-manager
rules:
- apiGroups: ["", "extensions", "apps"]
  resources: ["deployments", "replicasets", "pods"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"] # You can also use ["*"]
--
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: deployment-manager-binding
  namespace: my-scm
subjects:
- kind: User
  name: bouleau.r@sfeir.com
  apiGroup: ""
roleRef:
  kind: Role
  name: deployment-manager
  apiGroup: ""
